### ISSUE TITLE
Read conf from file

### ISSUE THREAD

**Issue by MattKetmo** [openl10n/openl10n-cli#1]
Example of configuration file

``` yml
server:
    host: openl10n.local
    login: user
    password: user

project: foobar

files:
    expr: 
        - src/Acme/Bundle/*/Resources/translations/<domain>.<local>.*
        - strings/<locale>/LC_MESSAGES/<domain>.*
    exclude: messages.en.yml

options: ~
```

Or specify credentials in user's home directory (`~/.openl10n.yml`):

```
hosts:
    openl10n.dev:
        user: user
        password: user
        #use_ssl: true
```

Then only use:

```
server: openl10n.dev
```
