### ISSUE TITLE
(Re) implements options for push & pull commands

### ISSUE THREAD

**Issue by MattKetmo** [openl10n/openl10n-cli#22]
See
- https://github.com/openl10n/openl10n-cli/commit/2372acccff8d5f6731ad7a947d5a9c8d3cf39240
- https://github.com/openl10n/openl10n/blob/master/src/Openl10n/Domain/Resource/Application/Action/ImportTranslationFileAction.php#L10
- https://github.com/openl10n/openl10n/blob/master/src/Openl10n/Domain/Resource/Application/Action/ExportTranslationFileAction.php#L9

``` yaml
files:
  - 
    pattern: path/to/<locale>.yml
    # File set specific options
    options: 
       push: [reviewed, erase, clean]
       pull: [reviewed, fallback_locale, fallback_key]

# Global options
options:
  push: [reviewed, erase, clean]
  pull: [reviewed, fallback_locale, fallback_key]
```
