### ISSUE TITLE
Language files at the root

### ISSUE THREAD

**Issue by MattKetmo** [openl10n/openl10n-cli#28]
The command is unable to detect language files when they are at the root of the project.

For instance: https://git.popcorntime.io/stash/projects/pt/repos/popcorn-i18n/browse

``` yml
server: dev
project: popcorn-i18n
files:
    - <locale>.json
```
