### ISSUE TITLE
Add option to export to different path

### ISSUE THREAD

**Issue by MattKetmo** [openl10n/openl10n-cli#3]
Example of conf file:

``` yaml
server: openl10n.dev
project: demo
files:
    expr: src/Openl10n/Bundle/*/Resources/translations/<domain>.<locale>.*
    export_to: app/Resources/translations/<domain>.<locale>.xlf
```
